version: '2'

services:
  solr_for_ellf:
    build:
      context: .
    container_name: solr4ent_for_ellf
    volumes:
      - ellf_index_archive:/Alfresco/solr/archive
      - ellf_index_workspace:/Alfresco/solr/workspace
      - ellf_logs:/opt/apache-tomcat-7.0.59/logs/
    ports:
     - "8081:8080"
     - "8801:8888"

volumes:
  ellf_index_archive:
  ellf_index_workspace:
  ellf_logs: